#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running lint-staged..."
npx lint-staged --allow-empty || exit 1

echo "🔒 Scanning for secrets with Gitleaks..."
gitleaks detect --no-git --exit-code 1 || exit 1
